# /admin/config.yml - CONFIGURED FOR MANUAL AUTH

backend:
  name: github
  repo: cheezfish/travel-lust-magazine # Your repo
  branch: main # Your main branch
  
  # These lines are now required for the manual auth flow
  base_url: https://travellustmagazine.com
  auth_endpoint: /api/auth # Points to your new function
  app_id: Ov23liEqTFb36oclI64c # Paste the Client ID from Step 2

# Optional but highly recommended for a better workflow
publish_mode: editorial_workflow

media_folder: "assets/images"
public_folder: "/assets/images"

# ... the rest of your collections ...
collections:
  - name: "issues"
    label: "Magazine Issues"
    folder: "issues"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Issue Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Make this the current Featured Issue?"
        name: "isFeatured"
        widget: "boolean"
        default: false
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - label: "Issue PDF"
        name: "pdf_file"
        widget: "file"
        media_folder: "assets/pdfs"
        public_folder: "/assets/pdfs"
        
  - name: "other_pages"
    label: "Other Pages"
    files:
      - file: "submissions.md"
        label: "Submissions Page"
        name: "submissions"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }